Решена задача 1
js-tasks-ru/jsbasic-20200727_svetlana23 pull request #1
Opened 2020-07-28 18:50 UTC by Svetlana-Romanova

2020-07-28 18:57 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
Первая задача
+ 1+1=2
```

Добавляю преподавателя (@stas-dolgachov) для код-ревью, посмотрим что он скажет :)

2020-07-29 09:07 UTC, dolgachio requested changes

2020-07-29 09:07 UTC, stas-dolgachov commented on 0-module/1-task/index.js
> +sum(6, 8);
Эта строчка здесь лишняя, в файлах с задачами не нужно вызывать функции, которые мы сами пишем, удалите ее, пожалуйста :)

2020-07-29 10:02 UTC, Svetlana-Romanova commented
Удалила. Нужно новый pull request создавать?

2020-07-29 10:02 UTC, jsru commented
@stas-dolgachov ping :)

2020-07-29 11:03 UTC, dolgachio approved these changes

2020-07-29 11:03 UTC, merged

2020-07-29 11:04 UTC, stas-dolgachov commented
> Удалила. Нужно новый pull request создавать?

Нет, такой необходимости нет :)
Спасибо, что учли мой комментарий