Решена задача 1 от Занятия 1
js-tasks-ru/jsbasic-20200727_svetlana23 pull request #2
Opened 2020-07-31 19:56 UTC by Svetlana-Romanova

2020-07-31 20:03 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
Вычислить факториал
+ факториал 1 равен 1
+ факториал 3 равен 6 
+ факториал 5 равен 120 
+ факториал 0 равен 1
```

Добавляю преподавателя (@stas-dolgachov) для код-ревью, посмотрим что он скажет :)

2020-08-01 09:24 UTC, dolgachio requested changes

2020-08-01 09:24 UTC, stas-dolgachov commented on 1-module/1-task/index.js
> +factorial(5);
Удалите, пожалуйста, эту строчку

2020-08-01 09:24 UTC, stas-dolgachov commented on 1-module/1-task/index.js
> +  }, 1);
А вы не хотите попробовать объединить логику из цикла и reduce?
Другими словами, сразу производить умножение в цикле for, чтобы избавиться от reduce. Это немного упростит решение :)
Понятно, что я имею в виду?

2020-08-01 17:27 UTC, Svetlana-Romanova commented on 1-module/1-task/index.js
> +  }, 1);
Переделала, но выглядит все равно как-то сложно. Или нормально?

2020-08-01 17:32 UTC, jsru commented
Пожалуйста, не меняйте «системные» файлы.
          Задача не может считаться решенной, если были изменены файлы тестов или другие «системные» файлы.
          Следующие файлы были изменены:
```diff
- 1-module/2-task/task.test.js — добавлен
```

2020-08-01 17:35 UTC, Svetlana-Romanova commented
Я не меняла системные файлы, а скачала 2 задачу. Это можно делать до разрешения пулл-реквеста?

2020-08-01 19:38 UTC, jsru commented
@stas-dolgachov ping :)

2020-08-01 20:50 UTC, Svetlana-Romanova commented
Совсем я запуталась в пул реквесте... уже и не пушит последнюю задачу

2020-08-01 20:51 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

```diff
Допишите функцию валидации имени пользователя
+ если содержит пробелы, то false
+ если меньше 4 символов то false
+ если имя корректное, то true
```
```diff
Сделать первый символ заглавным
+ должна делать первый символ заглавным
+ должна работать для строки из одной буквы
+ должна работать для пустой строки
```
```diff
Вычислить факториал
+ факториал 1 равен 1
+ факториал 3 равен 6 
+ факториал 5 равен 120 
+ факториал 0 равен 1
```
```diff
Проверка на спам
+ должна возвращать true для '1XbeT now'
+ должна возвращать false для 'innocent rabbit'
+ должна возвращать true для 'free xxxxx'
```
```diff
Усечение строки
- должна усекать строку 
- должна не трогать короткую строку 
```

2020-08-02 16:05 UTC, jsru commented
@stas-dolgachov ping :)

2020-08-03 13:56 UTC, Svetlana-Romanova commented
Все решено верно?

2020-08-04 19:37 UTC, jsru commented
@stas-dolgachov ping :)

2020-08-04 19:46 UTC, jsru commented
@stas-dolgachov ping :)

2020-08-05 06:32 UTC, dolgachio approved these changes
Прошу прощения, что не отвечал на ваши комментарии к пулл реквесту. 
Чтобы мне приходило уведомление, отмечайте меня, пожалуйста, вот так @stas-dolgachov .

Или пишите мне в Слак. 

Вы проделали отличную работу здесь, спасибо за решения!

2020-08-05 06:32 UTC, merged